- name: Download GRPC geyser
  become: true
  become_user: solana
  git:
    repo: 'https://github.com/rpcpool/yellowstone-grpc.git'
    dest: /home/solana/grpc-geyser
    version: tags/{{ geyser_version }}

- name: build geyser
  become: true
  become_user: solana
  shell: source /home/solana/.cargo/env && cargo build --release
  args:
    chdir: /home/solana/grpc-geyser
    executable: /bin/bash

- name: Save config
  become: true
  become_user: solana
  copy:
    src: grpc_config.json
    dest: /home/solana/grpc-config.json

- name: Add geyser config in validator.sh
  become: true
  become_user: solana
  lineinfile:
    path: /home/solana/validator.sh
    line: '--geyser-plugin-config /home/solana/grpc-config.json \'
    insertafter: '^--tpu-use-quic'

