- name: install snapshot requirements
  become: true
  become_user: solana
  ansible.builtin.pip:
    name:
      - tqdm
      - requests
    executable: pip3
    extra_args: --break-system-packages

- name: download latest snapshot
  become: true
  become_user: solana
  shell: python3 /mnt/snapshot-finder.py --snapshot_path /mnt/solana-ledger --version {{ solana_version }} --max_latency 150
